# ~/.bashrc - user-specific Bash settings
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi


# Put your fun stuff here.


# The pattern "**" used in a pathname expansion context will match
# all files and zero or more directories and subdirectories.
shopt -s globstar

# Extend the paths to the .local directories
path prepend -e bin ~/.local/bin
path append -e bin /usr/local/sbin /usr/sbin /sbin
path prepend -e lib ~/.local/lib64 ~/.local/lib
path prepend -e inc ~/.local/include
path prepend -e pkc ~/.local/lib/pkgconfig
path prepend -e man ~/.local/share/man

# Add Git key-less SSH keys to the SSH agent
ssh-add ".ssh/git@forge.rsa" ".ssh/git@github.rsa" ".ssh/git@gitorious.rsa.pub" ".ssh/laomaiweng,tclreadline@sourceforge.rsa" &> /dev/null

# Start or discover the GPG agent
export GPG_TTY=$(tty)
gpg-agent-test ~/.gnupg/agent-cobalt || gpg-agent --daemon --write-env-file ~/.gnupg/agent-cobalt
. ~/.gnupg/agent-cobalt
export GPG_AGENT_INFO

# Gentoo environment variables
export GENTOO_AUTHOR_NAME="Quentin Minster"
export GENTOO_AUTHOR_EMAIL=quentin@minster.io
export ECHANGELOG_USER="Quentin Minster <quentin@minster.io>"

# Exit from MC into last working directory
. /usr/libexec/mc/mc.sh

# If available, setup some useful aliases
[[ -f ~/.bash_aliases ]] && . ~/.bash_aliases

# Greet the user
[[ -f ~/.bash_greetings ]] && . ~/.bash_greetings

