# ~/.bashrc - user-specific Bash settings
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi


# Put your fun stuff here.


# The pattern "**" used in a pathname expansion context will match
# all files and zero or more directories and subdirectories.
shopt -s globstar

# Setup a useful history
HISTCONTROL=ignoreboth
HISTFILESIZE=-1
HISTSIZE=-1

# Source functions
if [[ -d ~/.bash_functions ]]; then
    for f in ~/.bash_functions/*; do
        [[ -x "$f" ]] && . "$f"
    done
fi

# Extend the paths to the .local directories (and some others)
path prepend -e bin ~/.local/bin ~/.cargo/bin
## Unused, pending future removal
# path prepend -e bin /usr/local/firejail                 # keep this last so that firejail'ed programs remain firejail'ed!
# path prepend -e lib ~/.local/lib64 ~/.local/lib
# path prepend -e inc ~/.local/include
# path prepend -e pkc ~/.local/lib/pkgconfig
# path prepend -e man ~/.local/share/man

# Default browser
export BROWSER=chromium

# Default location for the SSH agent socket under OpenRC user services
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.sock

# Gentoo environment variables
export GENTOO_AUTHOR_NAME="Quentin Minster"
export GENTOO_AUTHOR_EMAIL=quentin@minster.io
export PORTAGE_GPG_KEY=0x06C4FDF48B857706FDB4EE2E7427A13D9B5B7471
export ECHANGELOG_USER="Quentin Minster <quentin@minster.io>"

# Password store settings
export PASSWORD_STORE_ENABLE_EXTENSIONS="true"
export PASSWORD_STORE_SIGNING_KEY="06C4FDF48B857706FDB4EE2E7427A13D9B5B7471"

# *cough cough*
export DOTNET_CLI_TELEMETRY_OPTOUT=1


# Almost there, now either prepare interctive use, or exec a WM
# Launch our WM after logging into the first TTY (reserved for us by /etc/inittab)
if [[ -z "${WAYLAND_DISPLAY}" && "${XDG_VTNR}" -eq 1 ]]; then
    exec niri --session
fi

# Enable TODO auto-print
todo on -q

[[ -f ~/.bash_aliases ]] && . ~/.bash_aliases

command -v starship &>/dev/null && eval "$(starship init bash)"
