# ~/.bashrc - user-specific Bash settings
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi


# Put your fun stuff here.


# The pattern "**" used in a pathname expansion context will match
# all files and zero or more directories and subdirectories.
shopt -s globstar

# Setup a useful history
export HISTCONTROL=ignoreboth
export HISTFILESIZE=10000
export HISTSIZE=10000

# Extend the paths to the .local directories (and some others)
path prepend -e bin ~/.local/bin ~/.cargo/bin
path append -e bin /usr/local/sbin /usr/sbin /sbin
path prepend -e lib ~/.local/lib64 ~/.local/lib
path prepend -e inc ~/.local/include
path prepend -e pkc ~/.local/lib/pkgconfig
path prepend -e man ~/.local/share/man

# Add Git key-less SSH keys to the SSH agent
SSH_AGENT_AUTOKEYS=(~/.ssh/git@github.rsa ~/.ssh/git@gitorious.rsa ~/.ssh/laomaiweng,tclreadline@sourceforge.rsa)
ssh-agent-test ~/.ssh/agent-cobalt && ssh-add "${SSH_AGENT_AUTOKEYS[@]}" &> /dev/null || ssh-agent-respawn ~/.ssh/agent-cobalt

# GPG agent environment variables
export GPG_TTY=$(tty)

# Gentoo environment variables
export GENTOO_AUTHOR_NAME="Quentin Minster"
export GENTOO_AUTHOR_EMAIL=quentin@minster.io
export PORTAGE_GPG_KEY=0x0F5F912C
export ECHANGELOG_USER="Quentin Minster <quentin@minster.io>"

# Chromium default flags
export CHROMIUM_USER_FLAGS='--site-per-process --enable-potentially-annoying-security-features --enable-google-branded-context-menu --enable-grouped-history --enable-tcp-fastopen --enable-leak-detection' #--enable-wayland-server --enable-heap-profiling

# Source WeChall credentials
[[ -f ~/.wechallrc ]] && . ~/.wechallrc

# Default to no display when the X server is remote (this greatly improves Vim startup time over slow connections)
[[ "$DISPLAY" == "localhost:"* ]] && nodisplay

# If available, setup some useful aliases
[[ -f ~/.bash_aliases ]] && . ~/.bash_aliases

# Greet the user
[[ -f ~/.bash_greetings ]] && . ~/.bash_greetings

