# ~/.bash_aliases - user-specific aliases

alias screen='unset NOGREET ; screen'
alias tmux='unset NOGREET ; tmux'

alias mp3='mpg123 -v -C'
alias hd='hexdump -C'
alias line='head -n1'
alias git='hub'
alias g='git'
alias t='task'

alias strings='strings -a'  # http://lcamtuf.blogspot.fr/2014/10/psa-dont-run-strings-on-untrusted-files.html
alias gdb='gdb -q'
alias mkisofs='mkisofs -JR'
alias alsamixer='alsamixer -c PCH'

# vim:ft=sh
