# ~/.bash_aliases - user-specific aliases

# one-char shortcuts
alias g=git
alias p=print
alias t=task

# new names for specific options
alias l='ls -CF'
alias ll='ls -alh'
alias la='ls -A'
alias l.='ls -d .*'
alias lt='ls -alhct'
alias rcp='cp --reflink=always'

# options that should always be on
alias strings='strings -a'  # http://lcamtuf.blogspot.fr/2014/10/psa-dont-run-strings-on-untrusted-files.html
alias qsize='LC_ALL=C qsize'
alias sort='LC_ALL=C sort'  # https://twitter.com/hdmoore/status/808035256188235778
alias gdb='gdb -q'
alias readelf='readelf -W'
alias disown='disown -r'
alias pwgen='pwgen -cny -s'
alias hd='hexdump -f ~/.hd.cfg'

# machine-specific aliases
[ -f ~/.bash_aliases.local ] && . ~/.bash_aliases.local

# vim:ft=sh
